//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("2.1.3")]
[assembly: System.Reflection.AssemblyFileVersion("2.1.0.36600")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.1.3")]


